# Generated by Django 5.1.6 on 2025-03-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(help_text='Insert cats name', max_length=30, null='False')),
                ('add_date', models.DateTimeField(help_text='Insert date of ad', null='False')),
                ('age', models.IntegerField()),
                ('image', models.ImageField(upload_to=None)),
                ('adopt_status', models.CharField(choices=[('f', 'Free to adoption'), ('cn', 'curretnly unadoptable'), ('r', 'reserved')], default='f', help_text='Cats availability', max_length=5)),
            ],
            options={
                'ordering': ['-cat_name'],
            },
        ),
    ]
