# Generated by Django 5.1.6 on 2025-03-06 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_shelter', '0003_alter_cat_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=30, null=True, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ['-breed']},
        ),
        migrations.AlterField(
            model_name='cat',
            name='id',
            field=models.CharField(max_length=5, primary_key='True', serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cat_shelter.breed'),
        ),
    ]
