# Generated by Django 5.1.6 on 2025-03-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_shelter', '0004_breed_alter_cat_options_alter_cat_id_alter_cat_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='id',
            field=models.CharField(default='1', max_length=5, primary_key='True', serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
