# Generated by Django 5.1.6 on 2025-03-06 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_shelter', '0005_alter_cat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cat_shelter.breed'),
        ),
    ]
