# Generated by Django 5.1.6 on 2025-03-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat_shelter', '0007_alter_cat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='breed',
        ),
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ['-cat_name']},
        ),
        migrations.DeleteModel(
            name='Breed',
        ),
    ]
