# Generated by Django 5.1.6 on 2025-03-06 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_shelter', '0008_remove_cat_breed_alter_cat_options_delete_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=30, null=True, unique=True)),
            ],
            options={
                'ordering': ['-breed'],
            },
        ),
        migrations.AddField(
            model_name='cat',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cat_shelter.breed'),
        ),
    ]
