# Generated by Django 5.1.6 on 2025-03-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_shelter', '0011_alter_cat_adopt_status_alter_cat_deworming_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='adopt_status',
            field=models.CharField(choices=[('free', 'Free to adoption'), ('unadoptable', 'curretnly unadoptable'), ('reserved', 'reserved')], default='free', help_text='Cats availability', max_length=15),
        ),
        migrations.AlterField(
            model_name='cat',
            name='deworming',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=10),
        ),
        migrations.AlterField(
            model_name='cat',
            name='neutered',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=10),
        ),
        migrations.AlterField(
            model_name='cat',
            name='sex',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], default='female', max_length=10),
        ),
        migrations.AlterField(
            model_name='cat',
            name='vaccination',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=10),
        ),
    ]
