# Generated by Django 5.1.6 on 2025-03-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_shelter', '0012_alter_cat_adopt_status_alter_cat_deworming_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(upload_to='cat_images/'),
        ),
    ]
